spring.application.name=Auth Service

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5430/auth_db
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

jwt.access-token.expiration=3600
jwt.refresh-token.expiration=604800