spring.application.name=Receipt Service

server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5435/receipt_db
spring.datasource.username=postgres
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

pdf.storage.path=src/main/resources/pdfs/

payments.exchange.name=payments
payment.completed.queue=payment.completed
payment.completed.routing.key=payment.completed
